version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - prometheus
      - jaeger
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - monitoring

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3001:3000'
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - tempo

  tempo:
    image: grafana/tempo:latest
    ports:
      - '4317:4317'
      - '4318:4318'
    command: ['-config.file=/etc/tempo.yaml']
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml

networks:
  monitoring:
